FROM node:alpine AS build
ENV NODE_ENV=production
WORKDIR /frontend
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /frontend/build /usr/share/nginx/html
