apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: $CONTAINER_REGISTRY/simulator:$VERSION
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: rides-database
                  key: connection-string
            # - name: RESET_CUSTOMERS
            #   value: "true"
            # - name: RESET_DRIVERS
            #   value: "true"
