name: deploy backend service

on:
  push:
    branches:
      - "releases/**"
    paths:
      - "application/backend/**"
  # allows deployment to be invoked manually through the GitHub Actions user interface
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ vars.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.27.1

      - name: Build & Deploy
        run: ./deployment/kubernetes/cd/deploy.sh backend
